version: '3'

services:
  api:
    container_name: server
    build: './api'
    depends_on:
      - db
    ports:
      - 3333:3333
    networks:
       - production-network

  ui:
    container_name: front
    build: './app'
    depends_on:
      - api
    ports:
      - 3000:3000
    networks:
       - production-network
    

  db:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
       - production-network

networks:
  production-network: 
    driver: bridge
  
